# -*- coding: utf-8 -*-
"""CATÁLOGO SAT_N1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6Q6Z9ZHJHOmJNLXlPGsd4lPWnEKJMK8
"""

import streamlit as st
import pandas as pd

# Datos del catálogo (puedes cargar desde un CSV o definirlo en el script)
catalogo = [
    {"Código": "100", "Cuenta": "Activo"},
    {"Código": "100.01", "Cuenta": "Activo a corto plazo"},
    {"Código": "101", "Cuenta": "Caja"},
    {"Código": "102", "Cuenta": "Bancos"},
    {"Código": "103", "Cuenta": "Inversiones"},
    {"Código": "104", "Cuenta": "Otros instrumentos financieros"},
    {"Código": "105", "Cuenta": "Clientes"},
    {"Código": "106", "Cuenta": "Cuentas y documentos por cobrar a corto plazo"},
    {"Código": "107", "Cuenta": "Deudores diversos"},
    {"Codigo": "108","Cuenta":"Estimación de cuentas incobrables"},
    {"Codigo": "108","Cuenta":"Estimación de cuentas incobrables"},
    {"Codigo": "109","Cuenta":"Pagos anticipados"},
    {"Codigo": "110","Cuenta":"Subsidio al empleo por aplicar"},
    {"Codigo": "111","Cuenta":"Crédito al diesel por acreditar"},
    {"Codigo": "112","Cuenta":"Otros estímulos"},
    {"Codigo": "113","Cuenta":"Impuestos a favor"},
    {"Codigo": "114","Cuenta":"Pagos provisionales"},
    {"Codigo": "115","Cuenta":"Inventario"},
    {"Codigo": "116","Cuenta":"Estimación de inventarios obsoletos y de lento movimiento"},
    {"Codigo": "117","Cuenta":"Obras en proceso de inmuebles"},
    {"Codigo": "118","Cuenta":"Impuestos acreditables pagados"},
    {"Codigo": "119","Cuenta":"Impuestos acreditables por pagar"},
    {"Codigo": "120","Cuenta":"Anticipo a proveedores"},
    {"Codigo": "121","Cuenta":"Otros activos a corto plazo"},
    {"Codigo": "100.02","Cuenta":"Activo a largo plazo"},
    {"Codigo": "151","Cuenta":"Terrenos"},
    {"Codigo": "152","Cuenta":"Edificios"},
    {"Codigo": "153","Cuenta":"Maquinaria y equipo"},
    {"Codigo": "154","Cuenta":"Automóviles, autobuses, camiones de carga, tractocamiones, montacargas y remolques"},
    {"Codigo": "155","Cuenta":"Mobiliario y equipo de oficina"},
    {"Codigo": "156","Cuenta":"Equipo de cómputo"},
    {"Codigo": "157","Cuenta":"Equipo de comunicación"},
    {"Codigo": "158","Cuenta":"Activos biológicos, vegetales y semovientes"},
    {"Codigo": "159","Cuenta":"Obras en proceso de activos fijos"},
    {"Codigo": "160","Cuenta":"Otros activos fijos"},
    {"Codigo": "161","Cuenta":"Ferrocarriles"},
    {"Codigo": "162","Cuenta":"Embarcaciones"},
    {"Codigo": "163","Cuenta":"Aviones"},
    {"Codigo": "164","Cuenta":"Troqueles, moldes, matrices y herramental"},
    {"Codigo": "165","Cuenta":"Equipo de comunicaciones telefónicas"},
    {"Codigo": "166","Cuenta":"Equipo de comunicación satelital"},
    {"Codigo": "167","Cuenta":"Equipo de adaptaciones para personas con capacidades diferentes"},
    {"Codigo": "168","Cuenta":"Maquinaria y equipo de generación de energía de fuentes renovables o de sistemas de cogeneración de electricidad eficiente"},
    {"Codigo": "169","Cuenta":"Otra maquinaria y equipo"},
    {"Codigo": "170","Cuenta":"Adaptaciones y mejoras"},
    {"Codigo": "171","Cuenta":"Depreciación acumulada de activos fijos"},
    {"Codigo": "172","Cuenta":"Pérdida por deterioro acumulado de activos fijos"},
    {"Codigo": "173","Cuenta":"Gastos diferidos"},
    {"Codigo": "174","Cuenta":"Gastos pre operativos"},
    {"Codigo": "175","Cuenta":"Regalías, asistencia técnica y otros gastos diferidos"},
    {"Codigo": "176","Cuenta":"Activos intangibles"},
    {"Codigo": "177","Cuenta":"Gastos de organización"},
    {"Codigo": "178","Cuenta":"Investigación y desarrollo de mercado"},
    {"Codigo": "179","Cuenta":"Marcas y patentes"},
    {"Codigo": "180","Cuenta":"Crédito mercantil"},
    {"Codigo": "181","Cuenta":"Gastos de instalación"},
    {"Codigo": "182","Cuenta":"Otros activos diferidos"},
    {"Codigo": "183","Cuenta":"Amortización acumulada de activos diferidos"},
    {"Codigo": "184","Cuenta":"Depósitos en garantía"},
    {"Codigo": "185","Cuenta":"Impuestos diferidos"},
    {"Codigo": "186","Cuenta":"Cuentas y documentos por cobrar a largo plazo"},
    {"Codigo": "187","Cuenta":"Participación de los trabajadores en las utilidades diferidas"},
    {"Codigo": "188","Cuenta":"Inversiones permanentes en acciones"},
    {"Codigo": "189","Cuenta":"Estimación por deterioro de inversiones permanentes en acciones"},
    {"Codigo": "190","Cuenta":"Otros instrumentos financieros"},
    {"Codigo": "191","Cuenta":"Otros activos a largo plazo"},
    {"Codigo": "200","Cuenta":"Pasivo"},
    {"Codigo": "200.01","Cuenta":"Pasivo a corto plazo"},
    {"Codigo": "201","Cuenta":"Proveedores"},
    {"Codigo": "202","Cuenta":"Cuentas por pagar a corto plazo"},
    {"Codigo": "203","Cuenta":"Cobros anticipados a corto plazo"},
    {"Codigo": "204","Cuenta":"Instrumentos financieros a corto plazo"},
    {"Codigo": "205","Cuenta":"Acreedores diversos a corto plazo"},
    {"Codigo": "206","Cuenta":"Anticipo de cliente"},
    {"Codigo": "207","Cuenta":"Impuestos trasladados"},
    {"Codigo": "208","Cuenta":"Impuestos trasladados cobrados"},
    {"Codigo": "209","Cuenta":"Impuestos trasladados no cobrados"},
    {"Codigo": "210","Cuenta":"Provisión de sueldos y salarios por pagar"},
    {"Codigo": "211","Cuenta":"Provisión de contribuciones de seguridad social por pagar"},
    {"Codigo": "212","Cuenta":"Provisión de impuesto estatal sobre nómina por pagar"},
    {"Codigo": "213","Cuenta":"Impuestos y derechos por pagar"},
    {"Codigo": "214","Cuenta":"Dividendos por pagar"},
    {"Codigo": "215","Cuenta":"PTU por pagar"},
    {"Codigo": "216","Cuenta":"Impuestos retenidos"},
    {"Codigo": "217","Cuenta":"Pagos realizados por cuenta de terceros"},
    {"Codigo": "218","Cuenta":"Otros pasivos a corto plazo"},
    {"Codigo": "200.02","Cuenta":"Pasivo a largo plazo"},
    {"Codigo": "251","Cuenta":"Acreedores diversos a largo plazo"},
    {"Codigo": "252","Cuenta":"Cuentas por pagar a largo plazo"},
    {"Codigo": "253","Cuenta":"Cobros anticipados a largo plazo"},
    {"Codigo": "254","Cuenta":"Instrumentos financieros a largo plazo"},
    {"Codigo": "255","Cuenta":"Pasivos por beneficios a los empleados a largo plazo"},
    {"Codigo": "256","Cuenta":"Otros pasivos a largo plazo"},
    {"Codigo": "257","Cuenta":"Participación de los trabajadores en las utilidades diferida"},
    {"Codigo": "258","Cuenta":"Obligaciones contraídas de fideicomisos"},
    {"Codigo": "259","Cuenta":"Impuestos diferidos"},
    {"Codigo": "260","Cuenta":"Pasivos diferidos"},
    {"Codigo": "300","Cuenta":"Capital contable"},
    {"Codigo": "301","Cuenta":"Capital social"},
    {"Codigo": "302","Cuenta":"Patrimonio"},
    {"Codigo": "303","Cuenta":"Reserva legal"},
    {"Codigo": "304","Cuenta":"Resultado de ejercicios anteriores"},
    {"Codigo": "305","Cuenta":"Resultado del ejercicio"},
    {"Codigo": "306","Cuenta":"Otras cuentas de capital"},
    {"Codigo": "400","Cuenta":"Ingresos"},
    {"Codigo": "401","Cuenta":"Ingresos"},
    {"Codigo": "402","Cuenta":"Devoluciones, descuentos o bonificaciones sobre ingresos"},
    {"Codigo": "403","Cuenta":"Otros ingresos"},
    {"Codigo": "500","Cuenta":"Costos"},
    {"Codigo": "501","Cuenta":"Costo de venta y/o servicio"},
    {"Codigo": "502","Cuenta":"Compras"},
    {"Codigo": "503","Cuenta":"Devoluciones, descuentos o bonificaciones sobre compras"},
    {"Codigo": "504","Cuenta":"Otras cuentas de costos"},
    {"Codigo": "505","Cuenta":"Costo de activo fijo"},
    {"Codigo": "600","Cuenta":"Gastos"},
    {"Codigo": "601","Cuenta":"Gastos generales"},
    {"Codigo": "602","Cuenta":"Gastos de venta"},
    {"Codigo": "603","Cuenta":"Gastos de administración"},
    {"Codigo": "604","Cuenta":"Gastos de fabricación"},
    {"Codigo": "605","Cuenta":"Mano de obra directa"},
    {"Codigo": "606","Cuenta":"Facilidades administrativas fiscales"},
    {"Codigo": "607","Cuenta":"Participación de los trabajadores en las utilidades"},
    {"Codigo": "608","Cuenta":"Participación en resultados de subsidiarias"},
    {"Codigo": "609","Cuenta":"Participación en resultados de asociadas"},
    {"Codigo": "610","Cuenta":"Participación de los trabajadores en las utilidades diferida"},
    {"Codigo": "611","Cuenta":"Impuesto Sobre la renta"},
    {"Codigo": "612","Cuenta":"Gastos no deducibles para CUFIN"},
    {"Codigo": "613","Cuenta":"Depreciación contable"},
    {"Codigo": "614","Cuenta":"Amortización contable"},
    {"Codigo": "700","Cuenta":"Resultado integral de financiamiento"},
    {"Codigo": "701","Cuenta":"Gastos financieros"},
    {"Codigo": "702","Cuenta":"Productos financieros"},
    {"Codigo": "703","Cuenta":"Otros gastos"},
    {"Codigo": "704","Cuenta":"Otros productos"},
    {"Codigo": "800","Cuenta":"Cuentas de orden"},
    {"Codigo": "801","Cuenta":"UFIN del ejercicio"},
    {"Codigo": "802","Cuenta":"CUFIN del ejercicio"},
    {"Codigo": "803","Cuenta":"CUFIN de ejercicios anteriores"},
    {"Codigo": "804","Cuenta":"CUFINRE del ejercicio"},
    {"Codigo": "805","Cuenta":"CUFINRE de ejercicios anteriores"},
    {"Codigo": "806","Cuenta":"CUCA del ejercicio"},
    {"Codigo": "807","Cuenta":"CUCA de ejercicios anteriores"},
    {"Codigo": "808","Cuenta":"Ajuste anual por inflación acumulable"},
    {"Codigo": "809","Cuenta":"Ajuste anual por inflación deducible"},
    {"Codigo": "810","Cuenta":"Deducción de inversión"},
    {"Codigo": "811","Cuenta":"Utilidad o pérdida fiscal en venta y/o baja de activo fijo"},
    {"Codigo": "812","Cuenta":"Utilidad o pérdida fiscal en venta acciones o partes sociales"},
    {"Codigo": "813","Cuenta":"Pérdidas fiscales pendientes de amortizar actualizadas de ejercicios anteriores"},
    {"Codigo": "814","Cuenta":"Mercancías recibidas en consignación"},
    {"Codigo": "815","Cuenta":"Crédito fiscal de IVA e IEPS por la importación de mercancías para empresas certificadas"},
    {"Codigo": "816","Cuenta":"Crédito fiscal de IVA e IEPS por la importación de activos fijos para empresas certificadas"},
    {"Código": "899", "Cuenta": "Otras cuentas de orden"},
]

# Convertir a DataFrame
df = pd.DataFrame(catalogo)

# Mostrar imagen al inicio (ajusta la ruta o URL de la imagen)
st.image("UNRC.png", caption="Universidad Nacional Rosario Castellanos", width=350)


# Título de la App
st.title("Catálogo de Cuentas SAT")

# Filtros y búsqueda
st.sidebar.header("Filtros de búsqueda")

# Filtro por tipo general (Activo, Pasivo, etc.)
tipo = st.sidebar.selectbox(
    "Filtrar por tipo",
    ["Todos", "Activo", "Pasivo", "Capital contable", "Ingresos", "Costos", "Gastos", "Resultado integral de financiamiento", "Cuentas de orden"],
    index=0
)

# Filtro por código o nombre
buscar = st.sidebar.text_input("Buscar por código o nombre")

# Filtrar el DataFrame según lo seleccionado
df_filtrado = df.copy()

# Filtrar por tipo general
if tipo != "Todos":
    df_filtrado = df_filtrado[df_filtrado["Cuenta"].str.startswith(tipo)]

# Filtro de búsqueda por texto
if buscar:
    df_filtrado = df_filtrado[
        df_filtrado.apply(lambda row: buscar.lower() in row["Código"].lower() or buscar.lower() in row["Cuenta"].lower(), axis=1)
    ]

# Mostrar resultados
st.write(f"### Resultados ({len(df_filtrado)})")
st.dataframe(df_filtrado)

# Mostrar catálogo completo (opcional)
if st.checkbox("Mostrar catálogo completo"):
    st.write("### Catálogo Completo")
    st.dataframe(df)

# Pie de página
st.markdown("---")
st.markdown("App desarrollada en Streamlit para consulta de catálogo contable")